/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hefesto.hefestocomponentes.HFPassWordField;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author Flavio
 */
public class HFIcon extends JLabel {

    private String Cod;
    String name;

    /**
     * Creates new form HFIcon
     */
    public HFIcon() {
        initComponents();
        carregaListner();
    }

    public void carregaListner() {
        JPopupMenu menu = new JPopupMenu();
        JMenuItem it = new JMenuItem("Remover Icone");
        it.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                HFIcon.this.getParent().remove(HFIcon.this);
            }
        });
        menu.add(it);
        this.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    System.out.println(getCod());
                }
            }

        });
        this.setComponentPopupMenu(menu);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public String getCod() {
        return Cod;
    }

    public void setCod(String Cod) {
        this.Cod = Cod;
    }
}
