/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hefesto.hefestocomponentes.HFTabbedPane;

import com.hefesto.hefestocomponentes.HFTabbedButton.HFTabbedButton;
import java.awt.Component;
import javax.swing.Icon;
import javax.swing.JTabbedPane;

/**
 *
 * @author Flavio
 */
public class HFTabbedPane extends JTabbedPane {

    /**
     * Creates new form HFTabbedPane
     */
    boolean closable;

    public Boolean isClosable() {
        return closable;
    }

    public void setClosable(Boolean closable) {
        this.closable = closable;
    }

    public HFTabbedPane() {
        initComponents();

    }

    @Override
    public void addTab(String title, Component component) {
        super.addTab(title, component);
        if (closable) {
            this.setTabComponentAt(this.getTabCount() - 1,
                    new HFTabbedButton(this));
        }
    }

    @Override
    public void addTab(String title, Icon icon, Component component) {
        super.addTab(title, icon, component); //To change body of generated methods, choose Tools | Templates.
        if (closable) {
            this.setTabComponentAt(this.getTabCount() - 1,
                    new HFTabbedButton(this));
        }
    }

    @Override
    public void addTab(String title, Icon icon, Component component, String tip) {
        super.addTab(title, icon, component, tip); //To change body of generated methods, choose Tools | Templates.
        if (closable) {
            this.setTabComponentAt(this.getTabCount() - 1,
                    new HFTabbedButton(this));
        }
    }

    public void setAllclosable() {
        for (int i = 1; i < this.getComponentCount(); i++) {
            setTabAtIndexCloseabel(i-1);
        }
    }

    public void setTabAtIndexCloseabel(int i) {
        this.setTabComponentAt(i,
                new HFTabbedButton(this));
    }

    public void setComponentClosable(Component cmp) {
        setTabAtIndexCloseabel(this.getComponentZOrder(cmp));
    }
    
    public void setAllUnclosable(){
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
