/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hefesto.hefestocomponentes.HFLogon;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

/**
 *
 * @author flavio
 */
public class HFLoginPainel extends javax.swing.JPanel {

    /**
     * Creates new form HFLoginPainel
     */
    Boolean usuarioValidado = false;

    public HFLoginPainel() {
        initComponents();
        inicializaCampo(usuario);
        loginButton.setEnabled(false);
    }

    public void actionLogar(ActionListener evt) {
        loginButton.addActionListener(evt);
        loginButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        hFPasswordField1 = new com.hefesto.hefestocomponentes.HFPassWordField.HFPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 94, 160), 3));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Banner_Hefesto_Login3.png"))); // NOI18N

        jLabel2.setText("Login:");

        jLabel3.setText("Senha:");

        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioFocusLost(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        hFPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hFPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hFPasswordField1FocusLost(evt);
            }
        });
        hFPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hFPasswordField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hFPasswordField1KeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hFPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuario, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hFPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(loginButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.out.println("Adeus Mundo Cruel!");
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusLost
        if (usuario.getText().trim().length() == 0) {
            setError(usuario);
            usuarioValidado = false;
            loginButton.setEnabled((usuarioValidado && hFPasswordField1.valida()));
        } else {
            setOK(usuario);
            usuarioValidado = true;
            loginButton.setEnabled(usuarioValidado && hFPasswordField1.valida());
        }
    }//GEN-LAST:event_usuarioFocusLost

    private void usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusGained
        removeErro(usuario);
    }//GEN-LAST:event_usuarioFocusGained

    private void hFPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hFPasswordField1FocusGained
        hFPasswordField1.removeAlerts();
    }//GEN-LAST:event_hFPasswordField1FocusGained

    private void hFPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hFPasswordField1FocusLost
        hFPasswordField1.valida();
        loginButton.setEnabled((usuarioValidado && hFPasswordField1.valida()));
        if (loginButton.isEnabled()) {
            loginButton.grabFocus();
        }
    }//GEN-LAST:event_hFPasswordField1FocusLost

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void hFPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hFPasswordField1KeyTyped

    }//GEN-LAST:event_hFPasswordField1KeyTyped

    private void hFPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hFPasswordField1KeyReleased

    }//GEN-LAST:event_hFPasswordField1KeyReleased

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed
    /**
     * Retorna o Usuario que que deseja fazer o Login.
     *
     * @return
     */
    public String getUsuario() {
        return usuario.getText();
    }

    /**
     * retorna um array de char contendo a senha;
     *
     * @return
     */
    public String getSenha() {
        try {
            return hFPasswordField1.getSenha();
        } catch (Exception ex) {
            ex.printStackTrace();
            return "";
        }
    }

    /**
     * Marca componente como contendo valores invalidos.
     *
     * @param comp
     */
    public void setError(JComponent comp) {
        for (Component cmp : comp.getComponents()) {
            cmp.setVisible(true);
        }
        comp.setBorder(new LineBorder(Color.red));
    }

    /**
     * Remove a marcação de erro.
     *
     * @param comp
     */
    public void removeErro(JComponent comp) {
        for (Component cmp : comp.getComponents()) {
            cmp.setVisible(false);
        }
        comp.setBorder(new LineBorder(Color.LIGHT_GRAY));
    }

    public void setOK(JComponent comp) {
        for (Component cmp : comp.getComponents()) {
            if (cmp instanceof JLabel) {
                Icon b = new ImageIcon(new ImageIcon(getClass().getResource("/imagens/checkmark.png").getPath()).getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH));
                ((JLabel) cmp).setIcon(b);
                cmp.setVisible(true);
            }
        }
        comp.setBorder(new LineBorder(Color.GREEN));
    }

    /**
     * Inicializa os campos de texto.
     *
     * @param comp
     */
    public void inicializaCampo(JComponent comp) {
        Icon b = new ImageIcon(new ImageIcon(getClass().getResource("/imagens/cancel.png").getPath()).getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH));
        JLabel bb = new JLabel(b);
        comp.setLayout(new BorderLayout());
        bb.setSize(comp.getHeight(), comp.getHeight());
        comp.add(bb, BorderLayout.EAST);
        bb.setVisible(false);
    }

    public void msgErro(String erro) {
        jLabel4.setText(erro);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private com.hefesto.hefestocomponentes.HFPassWordField.HFPasswordField hFPasswordField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
